# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workflow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eworkflow.proto\x12\x0bworkflow.v1\"N\n\x14StartWorkflowRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x12\n\ntask_queue\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x01(\x0c\"\'\n\x15StartWorkflowResponse\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"?\n\x18GetWorkflowResultRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\">\n\x19GetWorkflowResultResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"P\n\x15SignalWorkflowRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x13\n\x0bsignal_name\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x01(\x0c\"\x18\n\x16SignalWorkflowResponse2\xa8\x02\n\x0fWorkflowService\x12V\n\rStartWorkflow\x12!.workflow.v1.StartWorkflowRequest\x1a\".workflow.v1.StartWorkflowResponse\x12\x62\n\x11GetWorkflowResult\x12%.workflow.v1.GetWorkflowResultRequest\x1a&.workflow.v1.GetWorkflowResultResponse\x12Y\n\x0eSignalWorkflow\x12\".workflow.v1.SignalWorkflowRequest\x1a#.workflow.v1.SignalWorkflowResponseBMZKgithub.com/livecodelife/linespec/examples/temporal-service/proto/workflowv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/livecodelife/linespec/examples/temporal-service/proto/workflowv1'
  _globals['_STARTWORKFLOWREQUEST']._serialized_start=31
  _globals['_STARTWORKFLOWREQUEST']._serialized_end=109
  _globals['_STARTWORKFLOWRESPONSE']._serialized_start=111
  _globals['_STARTWORKFLOWRESPONSE']._serialized_end=150
  _globals['_GETWORKFLOWRESULTREQUEST']._serialized_start=152
  _globals['_GETWORKFLOWRESULTREQUEST']._serialized_end=215
  _globals['_GETWORKFLOWRESULTRESPONSE']._serialized_start=217
  _globals['_GETWORKFLOWRESULTRESPONSE']._serialized_end=279
  _globals['_SIGNALWORKFLOWREQUEST']._serialized_start=281
  _globals['_SIGNALWORKFLOWREQUEST']._serialized_end=361
  _globals['_SIGNALWORKFLOWRESPONSE']._serialized_start=363
  _globals['_SIGNALWORKFLOWRESPONSE']._serialized_end=387
  _globals['_WORKFLOWSERVICE']._serialized_start=390
  _globals['_WORKFLOWSERVICE']._serialized_end=686
# @@protoc_insertion_point(module_scope)
