source "https://rubygems.org"

gem "rails", "~> 7.2.3"
gem "mysql2"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "httparty"
gem "ruby-kafka"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

gem "tzinfo-data", platforms: %i[ windows jruby ]
